# Generated by Django 4.2.28 on 2026-02-14 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_notification_notification_type_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core_app.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_billing_date',
            field=models.DateField(blank=True, help_text='Date of the next automatic recurring charge.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the subscription was paused.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_source_id',
            field=models.CharField(blank=True, help_text='Wompi payment source ID for recurring charges.', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, help_text='Wompi transaction ID for the initial payment.', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking confirmed'), ('booking_canceled', 'Booking canceled'), ('booking_rescheduled', 'Booking rescheduled'), ('booking_reminder', 'Booking reminder'), ('payment_confirmed', 'Payment confirmed'), ('receipt_email', 'Receipt email'), ('subscription_activated', 'Subscription activated'), ('subscription_canceled', 'Subscription canceled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core_app.booking'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=20),
        ),
    ]
