# Generated by Django 4.2.28 on 2026-02-15 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_wompi_subscription_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('reference', models.CharField(db_index=True, help_text='Unique Wompi payment reference.', max_length=255, unique=True)),
                ('wompi_transaction_id', models.CharField(blank=True, db_index=True, help_text='Wompi transaction ID returned on creation.', max_length=255)),
                ('payment_source_id', models.CharField(blank=True, help_text='Wompi payment source ID for recurring charges.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in the package currency (not cents).', max_digits=12)),
                ('currency', models.CharField(default='COP', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='core_app.package')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
