# Generated by Django 4.2.28 on 2026-02-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_create_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('personalizado', 'Personalizado'), ('semi_personalizado', 'Semi-personalizado'), ('terapeutico', 'Terapéutico')], db_index=True, default='personalizado', help_text='Program type used to group packages in the frontend.', max_length=30),
        ),
    ]
