# Generated by Django 4.2.28 on 2026-02-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_faqcategory_contactmessage_sitesettings_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='customer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payment_intents',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='pending_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='pending_first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='pending_last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='pending_password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='pending_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='public_access_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
