# Generated by Django 4.2.28 on 2026-02-16 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_payment_intent_guest_checkout_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core_app.availabilityslot'),
        ),
    ]
