# Generated by Django 4.2.28 on 2026-02-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_alter_booking_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expiry_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the expiry email reminder was sent.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiry_ui_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the expiry UI reminder was shown.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='Whether the subscription should be auto-renewed.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method_type',
            field=models.CharField(blank=True, default='', help_text='Wompi payment method type for the initial charge.', max_length=50),
        ),
    ]
