# Generated by Django 4.2.28 on 2026-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_subscription_expiry_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('booking_confirmed', 'Booking confirmed'),
                    ('booking_canceled', 'Booking canceled'),
                    ('booking_rescheduled', 'Booking rescheduled'),
                    ('booking_reminder', 'Booking reminder'),
                    ('payment_confirmed', 'Payment confirmed'),
                    ('receipt_email', 'Receipt email'),
                    ('subscription_activated', 'Subscription activated'),
                    ('subscription_canceled', 'Subscription canceled'),
                    ('subscription_expiry_reminder', 'Subscription expiry reminder'),
                ],
                max_length=50,
            ),
        ),
    ]
