# Generated by Django 4.2.28 on 2026-02-17 23:56

from django.db import migrations, models


def migrate_paused_subscriptions(apps, schema_editor):
    """Convert paused subscriptions to expired for paused state removal."""
    Subscription = apps.get_model('core_app', 'Subscription')
    Subscription.objects.filter(status='paused').update(
        status='expired',
        next_billing_date=None,
        sessions_used=models.F('sessions_total'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_add_subscription_expiry_reminder_notification_type'),
    ]

    operations = [
        migrations.RunPython(migrate_paused_subscriptions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subscription',
            name='paused_at',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=20),
        ),
    ]
