# Generated by Django 6.0.2 on 2026-03-07 01:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_remove_subscription_paused_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('sex', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=20)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Estatura en centímetros.', max_digits=5, null=True)),
                ('current_weight_kg', models.DecimalField(blank=True, decimal_places=1, help_text='Peso actual en kilogramos.', max_digits=5, null=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('primary_goal', models.CharField(blank=True, choices=[('fat_loss', 'Perder grasa'), ('muscle_gain', 'Ganar masa muscular'), ('rehab', 'Rehabilitación'), ('general_health', 'Salud general'), ('sports_performance', 'Rendimiento deportivo')], max_length=30)),
                ('kore_start_date', models.DateField(blank=True, help_text='Fecha de inicio en KÓRE. Se auto-asigna desde date_joined si no se indica.', null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__first_name',),
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('mood', models.CharField(choices=[('motivated', 'Motivado'), ('neutral', 'Neutral'), ('tired', 'Cansado / Desmotivado')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'mood entries',
                'ordering': ('-date',),
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('weight_kg', models.DecimalField(decimal_places=1, help_text='Peso en kilogramos.', max_digits=5)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'weight entries',
                'ordering': ('-date',),
                'unique_together': {('user', 'date')},
            },
        ),
    ]
