# Generated by Django 6.0.2 on 2026-03-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_password_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_failed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the last automatic billing attempt failed.', null=True),
        ),
    ]
