# Generated by Django 6.0.2 on 2026-03-09 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_add_billing_failed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('terms_version', models.CharField(default='v1.0', help_text='Version of the terms document that was accepted.', max_length=20)),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address at the time of acceptance.')),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser User-Agent string at the time of acceptance.')),
                ('accepted_at', models.DateTimeField(help_text='Exact timestamp when the user clicked accept.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-accepted_at',),
                'unique_together': {('user', 'terms_version')},
            },
        ),
    ]
