# Generated by Django 6.0.2 on 2026-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0016_add_terms_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección de residencia.', max_length=500),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del cliente.', null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='eps',
            field=models.CharField(blank=True, help_text='EPS del cliente.', max_length=255),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='id_expedition_date',
            field=models.DateField(blank=True, help_text='Fecha de expedición del documento.', null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='id_number',
            field=models.CharField(blank=True, help_text='Número de documento de identidad.', max_length=50),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='id_type',
            field=models.CharField(blank=True, choices=[('ti', 'Tarjeta de identidad'), ('cc', 'Cédula de ciudadanía'), ('ce', 'Cédula de extranjería'), ('pasaporte', 'Pasaporte'), ('dni', 'DNI')], help_text='Tipo de documento de identidad.', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='current_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Peso actual en kilogramos (dato del entrenador).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Estatura en centímetros (dato del entrenador).', max_digits=5, null=True),
        ),
    ]
