# Generated by Django 6.0.2 on 2026-03-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0017_add_customer_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='current_weight_kg',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='height_cm',
        ),
    ]
