# Generated by Django 6.0.2 on 2026-03-10 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0020_add_anthropometry_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anthropometryevaluation',
            name='abdomen_cm',
        ),
        migrations.RemoveField(
            model_name='anthropometryevaluation',
            name='arm_flexed_cm',
        ),
        migrations.RemoveField(
            model_name='anthropometryevaluation',
            name='arm_relaxed_cm',
        ),
        migrations.RemoveField(
            model_name='anthropometryevaluation',
            name='calf_cm',
        ),
        migrations.RemoveField(
            model_name='anthropometryevaluation',
            name='chest_cm',
        ),
        migrations.RemoveField(
            model_name='anthropometryevaluation',
            name='neck_cm',
        ),
        migrations.RemoveField(
            model_name='anthropometryevaluation',
            name='thigh_cm',
        ),
        migrations.AddField(
            model_name='anthropometryevaluation',
            name='asymmetries',
            field=models.JSONField(blank=True, default=dict, help_text='Detected bilateral asymmetries >10%.'),
        ),
        migrations.AddField(
            model_name='anthropometryevaluation',
            name='bf_method',
            field=models.CharField(blank=True, help_text='jackson_pollock or deurenberg', max_length=30),
        ),
        migrations.AddField(
            model_name='anthropometryevaluation',
            name='perimeters',
            field=models.JSONField(blank=True, default=dict, help_text='Perímetros en cm. Keys: brazo_relajado_d/i, brazo_flexionado_d/i, antebrazo_d/i, muneca_d/i, pecho, cintura, gluteos, muslo_d/i, pantorrilla_d/i, tobillo_d/i.'),
        ),
        migrations.AddField(
            model_name='anthropometryevaluation',
            name='skinfolds',
            field=models.JSONField(blank=True, default=dict, help_text='Pliegues en mm. Keys: triceps_d/i, biceps_d/i, subescapular_d/i, cresta_iliaca_d/i, supraespinal, abdominal, muslo_d/i, pantorrilla_d/i.'),
        ),
        migrations.AddField(
            model_name='anthropometryevaluation',
            name='sum_skinfolds',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometryevaluation',
            name='age_at_evaluation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometryevaluation',
            name='height_cm',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='anthropometryevaluation',
            name='hip_cm',
            field=models.DecimalField(decimal_places=1, help_text='Glúteos / cadera.', max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='anthropometryevaluation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anthropometryevaluation',
            name='waist_cm',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='anthropometryevaluation',
            name='weight_kg',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
