# Generated by Django 6.0.2 on 2026-03-16 19:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0024_physical_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('meals_per_day', models.PositiveSmallIntegerField(help_text='Número de comidas al día.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('water_liters', models.DecimalField(decimal_places=1, help_text='Litros de agua al día.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('fruit_weekly', models.PositiveSmallIntegerField(help_text='Frecuencia semanal de consumo de frutas.', validators=[django.core.validators.MaxValueValidator(35)])),
                ('vegetable_weekly', models.PositiveSmallIntegerField(help_text='Frecuencia semanal de consumo de verduras.', validators=[django.core.validators.MaxValueValidator(35)])),
                ('protein_frequency', models.PositiveSmallIntegerField(help_text='Frecuencia de proteína (1=nunca, 5=diario en cada comida).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ultraprocessed_weekly', models.PositiveSmallIntegerField(help_text='Frecuencia semanal de ultraprocesados.', validators=[django.core.validators.MaxValueValidator(35)])),
                ('sugary_drinks_weekly', models.PositiveSmallIntegerField(help_text='Frecuencia semanal de bebidas azucaradas.', validators=[django.core.validators.MaxValueValidator(35)])),
                ('eats_breakfast', models.BooleanField(help_text='¿Desayuna regularmente?')),
                ('notes', models.TextField(blank=True)),
                ('habit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('habit_category', models.CharField(blank=True, max_length=30)),
                ('habit_color', models.CharField(blank=True, max_length=10)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ParqAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('q1_heart_condition', models.BooleanField(default=False, help_text='¿Algún médico le ha dicho que tiene una condición cardíaca O presión arterial alta?')),
                ('q2_chest_pain', models.BooleanField(default=False, help_text='¿Siente dolor en el pecho en reposo, en actividades diarias, o al hacer actividad física?')),
                ('q3_dizziness', models.BooleanField(default=False, help_text='¿Pierde el equilibrio por mareos O ha perdido el conocimiento en los últimos 12 meses?')),
                ('q4_chronic_condition', models.BooleanField(default=False, help_text='¿Le han diagnosticado alguna condición médica crónica (diferente a enfermedad cardíaca o presión alta)?')),
                ('q5_prescribed_medication', models.BooleanField(default=False, help_text='¿Actualmente toma medicamentos recetados para una condición médica crónica?')),
                ('q6_bone_joint_problem', models.BooleanField(default=False, help_text='¿Tiene actualmente (o ha tenido en los últimos 12 meses) un problema óseo, articular o de tejidos blandos que podría empeorar con actividad física?')),
                ('q7_medical_supervision', models.BooleanField(default=False, help_text='¿Algún médico le ha dicho que solo debe hacer actividad física con supervisión médica?')),
                ('additional_notes', models.TextField(blank=True)),
                ('yes_count', models.PositiveSmallIntegerField(default=0)),
                ('risk_classification', models.CharField(blank=True, max_length=30)),
                ('risk_label', models.CharField(blank=True, max_length=50)),
                ('risk_color', models.CharField(blank=True, max_length=10)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='parq_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
