# Generated by Django 6.0.2 on 2026-03-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0025_nutrition_habit_and_parq_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking confirmed'), ('booking_canceled', 'Booking canceled'), ('booking_rescheduled', 'Booking rescheduled'), ('booking_reminder', 'Booking reminder'), ('payment_confirmed', 'Payment confirmed'), ('receipt_email', 'Receipt email'), ('subscription_activated', 'Subscription activated'), ('subscription_canceled', 'Subscription canceled'), ('subscription_expiry_reminder', 'Subscription expiry reminder'), ('nutrition_reminder', 'Nutrition reminder'), ('parq_reminder', 'PAR-Q reminder')], max_length=50),
        ),
    ]
