# Generated by Django 6.0.2 on 2026-04-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0026_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anthropometryevaluation',
            options={'ordering': ('-evaluation_date',)},
        ),
        migrations.AlterModelOptions(
            name='physicalevaluation',
            options={'ordering': ('-evaluation_date',)},
        ),
        migrations.AlterModelOptions(
            name='posturometryevaluation',
            options={'ordering': ('-evaluation_date',)},
        ),
    ]
