# Generated by Django 6.0.2 on 2026-04-27 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0028_registrationverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, choices=[('wompi', 'Wompi'), ('payu', 'PayU'), ('epayco', 'ePayco'), ('paypal', 'PayPal'), ('cash', 'Efectivo')], max_length=20),
        ),
        migrations.CreateModel(
            name='SubscriptionGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('invited_email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('revoked', 'Revocado')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guest_link', to='core_app.subscription')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
