# Generated by Django 6.0.2 on 2026-05-01 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0029_subscription_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('pattern', models.CharField(blank=True, max_length=100)),
                ('exercise_type', models.CharField(blank=True, max_length=100)),
                ('main_implement', models.CharField(blank=True, max_length=100)),
                ('primary_muscles', models.CharField(blank=True, max_length=255)),
                ('secondary_muscles', models.CharField(blank=True, max_length=255)),
                ('plane', models.CharField(blank=True, max_length=50)),
                ('explanation', models.TextField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('fitness_level_min', models.PositiveSmallIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_corrective', models.BooleanField(db_index=True, default=False)),
                ('goal_tags', models.JSONField(default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking confirmed'), ('booking_canceled', 'Booking canceled'), ('booking_rescheduled', 'Booking rescheduled'), ('booking_reminder', 'Booking reminder'), ('payment_confirmed', 'Payment confirmed'), ('receipt_email', 'Receipt email'), ('subscription_activated', 'Subscription activated'), ('subscription_canceled', 'Subscription canceled'), ('subscription_expiry_reminder', 'Subscription expiry reminder'), ('nutrition_reminder', 'Nutrition reminder'), ('parq_reminder', 'PAR-Q reminder'), ('duo_invitation', 'Duo invitation')], max_length=50),
        ),
    ]
