# Generated by Django 6.0.2 on 2026-05-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0031_monthly_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('proteina', 'Proteína'), ('carbohidrato', 'Carbohidrato'), ('grasa_saludable', 'Grasa saludable'), ('fruta', 'Fruta'), ('verdura', 'Verdura'), ('lacteo', 'Lácteo'), ('snack', 'Snack'), ('bebida', 'Bebida')], max_length=30)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('protein_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbs_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fat_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fiber_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nova_group', models.PositiveSmallIntegerField(blank=True, help_text='1=unprocessed … 4=ultra-processed', null=True)),
                ('nutri_score', models.CharField(blank=True, help_text='A–E', max_length=1)),
                ('source', models.CharField(choices=[('taco', 'TACO Brasil'), ('openfoodfacts', 'Open Food Facts'), ('curated', 'Curado manualmente')], default='curated', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='core_app_fo_categor_1441de_idx'), models.Index(fields=['is_active'], name='core_app_fo_is_acti_b64dbb_idx')],
                'unique_together': {('name', 'source')},
            },
        ),
        migrations.CreateModel(
            name='MealSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('meal_block', models.CharField(choices=[('desayuno', 'Desayuno'), ('media_manana', 'Media mañana'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('calories_estimate', models.PositiveSmallIntegerField()),
                ('goal_tags', models.JSONField(default=list, help_text='e.g. ["fat_loss", "muscle_gain", "general_health"]')),
                ('fitness_level_min', models.PositiveSmallIntegerField(default=1)),
                ('fitness_level_max', models.PositiveSmallIntegerField(default=5)),
                ('nova_max', models.PositiveSmallIntegerField(default=2, help_text='Max NOVA group allowed in this suggestion')),
                ('is_active', models.BooleanField(default=True)),
                ('foods', models.ManyToManyField(blank=True, related_name='meal_suggestions', to='core_app.food')),
            ],
            options={
                'indexes': [models.Index(fields=['meal_block', 'is_active'], name='core_app_me_meal_bl_058902_idx')],
            },
        ),
    ]
