# Generated by Django 6.0.2 on 2026-05-05 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0032_food_and_meal_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('meal_block', models.CharField(choices=[('desayuno', 'Desayuno'), ('media_manana', 'Media mañana'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('not_done', 'Not Done')], default='not_done', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='nutrition/%Y/%m/')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_entries', to='core_app.mealsuggestion')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to='core_app.nutritiondailylog')),
            ],
            options={
                'unique_together': {('daily_log', 'meal_block')},
            },
        ),
    ]
