# Generated by Django 6.0.2 on 2026-05-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0033_nutrition_daily_log_and_meal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session_notes_for_customer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='session_objective',
            field=models.TextField(blank=True),
        ),
    ]
