# Generated by Django 6.0.2 on 2026-05-05 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0034_booking_session_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='flagged_for_session',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='trainer_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='trainer_comment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyprogram',
            name='adjustment_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monthlyprogram',
            name='is_paused',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='monthlyprogram',
            name='pause_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='monthlyprogram',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClientRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo'), ('sin_riesgo', 'Sin riesgo')], db_index=True, default='sin_riesgo', max_length=20)),
                ('kore_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('behavioral_signals', models.JSONField(default=list)),
                ('clinical_signals', models.JSONField(default=list)),
                ('is_stale', models.BooleanField(db_index=True, default=False)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_risk_scores', to='core_app.trainerprofile')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerAlertResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('signal_type', models.CharField(max_length=50)),
                ('resolution_type', models.CharField(choices=[('private_note', 'Nota privada'), ('public_note', 'Nota pública'), ('schedule_eval', 'Agendar evaluación'), ('mark_reviewed', 'Marcar revisado'), ('go_to_module', 'Ir al módulo')], max_length=30)),
                ('note', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='core_app.clientriskscore')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_resolutions', to='core_app.trainerprofile')),
            ],
            options={
                'ordering': ['-resolved_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('trigger_type', models.CharField(choices=[('post_session', 'Post sesión'), ('post_milestone', 'Post hito'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('trigger_ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('seen_by_customer', models.BooleanField(db_index=True, default=False)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_messages', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core_app.trainerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientriskscore',
            index=models.Index(fields=['customer', 'trainer', 'is_stale'], name='core_app_cl_custome_85913e_idx'),
        ),
    ]
