# Generated by Django 6.0.2 on 2026-05-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0035_mealentry_flagged_for_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainermessage',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
