# Generated by Django 6.0.2 on 2026-05-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0037_user_is_deleted_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, choices=[('wompi', 'Wompi'), ('payu', 'PayU'), ('epayco', 'ePayco'), ('paypal', 'PayPal'), ('cash', 'Efectivo'), ('transfer', 'Transferencia')], max_length=20),
        ),
    ]
