# Generated by Django 6.0.2 on 2026-05-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0040_nutrition_habit_trainer_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='fitness_level_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nivel de condición física asignado manualmente por el entrenador (1–5). Si es nulo se calcula automáticamente desde la última evaluación física.', null=True),
        ),
    ]
