# Generated by Django 6.0.2 on 2026-05-11 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0041_customerprofile_fitness_level_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyNutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('goal', models.CharField(max_length=50)),
                ('fitness_level', models.PositiveSmallIntegerField()),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('trainer_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_nutrition_plans', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_nutrition_plans', to='core_app.trainerprofile')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('day_number', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core_app.weeklynutritionplan')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('meal_block', models.CharField(choices=[('desayuno', 'Desayuno'), ('media_manana', 'Media mañana'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('trainer_notes', models.TextField(blank=True)),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core_app.weeklyplanday')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_meals', to='core_app.mealsuggestion')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('plan_day', 'meal_block')},
            },
        ),
    ]
