# Generated by Django 6.0.2 on 2026-05-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0042_weekly_nutrition_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
