# Generated by Django 6.0.2 on 2026-05-13 05:01

from django.db import migrations


def copy_slot_times(apps, schema_editor):
    Booking = apps.get_model('core_app', 'Booking')
    for b in Booking.objects.select_related('slot').iterator():
        if b.slot_id and (b.starts_at is None or b.ends_at is None):
            b.starts_at = b.slot.starts_at
            b.ends_at = b.slot.ends_at
            b.save(update_fields=['starts_at', 'ends_at'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0043_booking_starts_ends_nullable'),
    ]

    operations = [
        migrations.RunPython(copy_slot_times, noop),
    ]
