# Generated by Django 6.0.2 on 2026-05-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0046_drop_availability_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='payment_method_type',
            field=models.CharField(blank=True, default='', help_text='Wompi payment_method_type for this intent (CARD, NEQUI, BANCOLOMBIA_TRANSFER, PSE).', max_length=40),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='wompi_authorization_url',
            field=models.URLField(blank=True, default='', help_text='Bancolombia authorization URL the customer must visit before confirm.', max_length=2000),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='wompi_bancolombia_token_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Bancolombia Transfer token id returned by POST /tokens/bancolombia_transfer.', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='wompi_nequi_token_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Nequi token id returned by POST /tokens/nequi (recurring flow).', max_length=255),
        ),
    ]
