# Generated by Django 6.0.2 on 2026-05-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0047_paymentintent_payment_method_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WompiEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('transaction_id', models.CharField(db_index=True, help_text='Wompi transaction.id from the webhook payload.', max_length=255, unique=True)),
                ('status', models.CharField(help_text='Terminal status observed (APPROVED/DECLINED/VOIDED/ERROR).', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-processed_at',),
            },
        ),
    ]
