# Generated by Django 6.0.2 on 2026-05-15 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0048_wompievent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterGlassLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('photo', models.ImageField(upload_to='nutrition/water/%Y/%m/')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_glasses', to='core_app.nutritiondailylog')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
