# Generated by Django 6.0.2 on 2026-05-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0049_water_glass_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealentry',
            name='flagged_for_session',
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='trainer_comment',
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='trainer_comment_at',
        ),
    ]
