# Generated by Django 6.0.5 on 2026-05-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0050_remove_meal_trainer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.TextField(blank=True),
        ),
    ]
