# Generated by Django 6.0.2 on 2026-05-22 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0051_alter_exercise_muscles_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionWeekNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('cycle_number', models.PositiveSmallIntegerField()),
                ('cycle_start', models.DateField()),
                ('week_number', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_week_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cycle_number', 'week_number'],
                'unique_together': {('customer', 'cycle_number', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='ProgramWeekNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_notes', to='core_app.monthlyprogram')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('program', 'week_number')},
            },
        ),
    ]
