# Generated by Django 6.0.5 on 2026-06-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0052_nutritionweeknote_programweeknote'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='anthropometryevaluation',
            index=models.Index(fields=['customer', '-evaluation_date'], name='anthro_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalevaluation',
            index=models.Index(fields=['customer', '-evaluation_date'], name='physeval_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='posturometryevaluation',
            index=models.Index(fields=['customer', '-evaluation_date'], name='postur_customer_date_idx'),
        ),
    ]
