# Generated by Django 6.0.2 on 2026-06-08 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0053_anthropometryevaluation_anthro_customer_date_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField(help_text='Local Bogota date (YYYY-MM-DD) on which no new bookings are allowed.')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='core_app.trainerprofile')),
            ],
            options={
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['trainer', 'date'], name='core_app_tr_trainer_043d8c_idx')],
                'constraints': [models.UniqueConstraint(fields=('trainer', 'date'), name='uniq_trainer_unavailability_date')],
            },
        ),
    ]
