# Generated by Django 6.0.2 on 2026-06-22 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0054_trainerunavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('kind', models.CharField(choices=[('initial', 'Initial purchase'), ('manual', 'Manual renewal'), ('automatic', 'Automatic renewal'), ('plan_change', 'Plan change')], max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('sessions_granted', models.PositiveIntegerField()),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_records', to='core_app.package')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_records', to='core_app.payment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='core_app.subscription')),
            ],
            options={
                'ordering': ('-period_start',),
            },
        ),
    ]
