# Generated by Django 6.0.2 on 2026-07-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0055_subscriptionrenewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Subscription canceled but access is retained until expires_at; recurring billing is stopped. Flipped to CANCELED at expiry.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_package',
            field=models.ForeignKey(blank=True, help_text='Package scheduled to take effect at the next renewal (downgrade / lateral plan change). Applied and cleared on renewal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_subscriptions', to='core_app.package'),
        ),
    ]
