# Generated by Django 6.0.2 on 2026-07-02 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0056_subscription_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='medium', max_length=10)),
                ('action_values', models.JSONField(blank=True, default=dict)),
                ('streak_bonuses', models.JSONField(blank=True, default=dict)),
                ('training_day_threshold', models.FloatField(default=0.7)),
                ('nutrition_min_meals', models.PositiveSmallIntegerField(default=3)),
                ('water_goal_glasses', models.PositiveSmallIntegerField(default=8)),
                ('meal_review_days', models.PositiveSmallIntegerField(default=3)),
                ('reschedule_window_hours', models.PositiveSmallIntegerField(default=24)),
                ('require_workout_captures', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='attendance_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='attendance_status',
            field=models.CharField(choices=[('unset', 'Unset'), ('attended', 'Attended'), ('no_show', 'No Show')], db_index=True, default='unset', max_length=10),
        ),
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('balance', models.IntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.ImageField(upload_to='workout_captures/%Y/%m/')),
                ('exercise_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='core_app.exerciselog')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PhysicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('performed_at', models.DateField(db_index=True)),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='physical_tests', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_tests', to='core_app.trainerprofile')),
            ],
            options={
                'ordering': ('-performed_at',),
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('action', models.CharField(choices=[('physical_test_passed', 'Physical test passed'), ('session_attended', 'Session attended'), ('workout_day', 'Workout day'), ('meal_photo', 'Meal with photo'), ('checkin', 'Daily check-in'), ('water_goal', 'Hydration goal'), ('streak_bonus', 'Streak bonus'), ('no_show_penalty', 'No-show penalty'), ('no_show_reversal', 'No-show reversal'), ('late_reschedule_penalty', 'Late reschedule penalty'), ('adjustment', 'Manual adjustment')], db_index=True, max_length=32)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='confirmed', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('reference_type', models.CharField(blank=True, default='', max_length=32)),
                ('reference_id', models.CharField(blank=True, max_length=64, null=True)),
                ('review_deadline', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('customer', 'action', 'reference_type', 'reference_id'), name='uq_credit_tx_reference')],
            },
        ),
    ]
