# Generated by Django 6.0.2 on 2026-07-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0057_creditsettings_booking_attendance_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='energy_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Energy 1 (agotado) to 5 (a tope). Optional check-in extra.', null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='pain',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='ready_to_train',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
