# Generated by Django 6.0.2 on 2026-07-02 20:17

from django.db import migrations


def enable_workout_captures(apps, schema_editor):
    """Ship the workout camera flow and the credits rule together (Part 2).

    Flips the deployed CreditSettings singleton; fresh installs keep the model
    default (False) until this migration runs after seeding.
    """
    CreditSettings = apps.get_model('core_app', 'CreditSettings')
    CreditSettings.objects.filter(pk=1).update(require_workout_captures=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0058_moodentry_energy_level_moodentry_pain_and_more'),
    ]

    operations = [
        migrations.RunPython(enable_workout_captures, migrations.RunPython.noop),
    ]
