# Generated by Django 6.0.2 on 2026-07-04 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0059_enable_workout_captures'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_items/')),
                ('price_credits', models.PositiveIntegerField()),
                ('item_type', models.CharField(choices=[('servicio', 'Servicio'), ('producto', 'Producto físico'), ('sesion_adicional', 'Sesión adicional'), ('descuento', 'Descuento')], default='servicio', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('-is_active', 'price_credits', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='action',
            field=models.CharField(choices=[('physical_test_passed', 'Physical test passed'), ('session_attended', 'Session attended'), ('workout_day', 'Workout day'), ('meal_photo', 'Meal with photo'), ('checkin', 'Daily check-in'), ('water_goal', 'Hydration goal'), ('streak_bonus', 'Streak bonus'), ('no_show_penalty', 'No-show penalty'), ('no_show_reversal', 'No-show reversal'), ('late_reschedule_penalty', 'Late reschedule penalty'), ('adjustment', 'Manual adjustment'), ('redemption', 'Store redemption'), ('redemption_refund', 'Redemption refund')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='RedemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('credits_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('fulfilled', 'Entregado'), ('rejected', 'Rechazado')], db_index=True, default='pending', max_length=10)),
                ('trainer_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='core_app.storeitem')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
