# Generated by Django 6.0.2 on 2026-07-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0060_storeitem_alter_credittransaction_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='delivery_photo',
            field=models.ImageField(blank=True, null=True, upload_to='redemption_deliveries/'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='item_type',
            field=models.CharField(choices=[('servicio', 'Servicio'), ('producto', 'Producto físico'), ('sesion_adicional', 'Sesión adicional')], default='servicio', max_length=20),
        ),
    ]
