# Generated by Django 6.0.2 on 2026-07-07 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0062_remap_descuento_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='sessions_granted',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SessionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sessions_total', models.PositiveIntegerField()),
                ('sessions_used', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_grants', to=settings.AUTH_USER_MODEL)),
                ('source_redemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_grants', to='core_app.redemptionrequest')),
            ],
            options={
                'ordering': ('expires_at',),
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='session_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core_app.sessiongrant'),
        ),
    ]
