# Generated by Django 6.0.2 on 2026-07-07 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0063_session_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('credits', models.PositiveIntegerField()),
                ('price_cop', models.PositiveIntegerField(help_text='Whole COP (no cents).')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('price_cop',),
            },
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='action',
            field=models.CharField(choices=[('physical_test_passed', 'Physical test passed'), ('session_attended', 'Session attended'), ('workout_day', 'Workout day'), ('meal_photo', 'Meal with photo'), ('checkin', 'Daily check-in'), ('water_goal', 'Hydration goal'), ('streak_bonus', 'Streak bonus'), ('no_show_penalty', 'No-show penalty'), ('no_show_reversal', 'No-show reversal'), ('late_reschedule_penalty', 'Late reschedule penalty'), ('adjustment', 'Manual adjustment'), ('redemption', 'Store redemption'), ('redemption_refund', 'Redemption refund'), ('purchase', 'Credit purchase')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('credits', models.PositiveIntegerField()),
                ('amount_cop', models.PositiveIntegerField()),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='pending', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('credit_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core_app.creditpackage')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
