# Generated by Django 6.0.2 on 2026-07-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0064_credit_topup'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='includes_nutrition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='includes_nutrition',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
