# Generated by Django 6.0.2 on 2026-07-14 20:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0067_enable_workout_captures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='action',
            field=models.CharField(choices=[('physical_test_passed', 'Physical test passed'), ('session_attended', 'Session attended'), ('session_rated', 'Session rated'), ('workout_day', 'Workout day'), ('meal_photo', 'Meal with photo'), ('checkin', 'Daily check-in'), ('water_goal', 'Hydration goal'), ('streak_bonus', 'Streak bonus'), ('no_show_penalty', 'No-show penalty'), ('no_show_reversal', 'No-show reversal'), ('late_reschedule_penalty', 'Late reschedule penalty'), ('adjustment', 'Manual adjustment'), ('redemption', 'Store redemption'), ('redemption_refund', 'Redemption refund'), ('purchase', 'Credit purchase')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='SessionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rater_role', models.CharField(choices=[('customer', 'Customer'), ('trainer', 'Trainer')], db_index=True, max_length=10)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core_app.booking')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('booking', 'rater_role'), name='uniq_rating_per_booking_role')],
            },
        ),
    ]
