export const FlowTags = {
  AUTH_LOGIN: ['@flow:auth-login', '@module:auth', '@priority:P1'],
  AUTH_LOGOUT: ['@flow:auth-logout', '@module:auth', '@priority:P2'],
  AUTH_SESSION_PERSISTENCE: ['@flow:auth-session-persistence', '@module:auth', '@priority:P2'],
  AUTH_TOKEN_REFRESH: ['@flow:auth-token-refresh', '@module:auth', '@priority:P2'],
  AUTH_REGISTER: ['@flow:auth-register', '@module:auth', '@priority:P1'],
  AUTH_PROTECTED_ROUTES: ['@flow:auth-protected-routes', '@module:auth', '@priority:P2'],

  BOOKING_SESSION_PAGE: ['@flow:booking-session-page', '@module:booking', '@priority:P1'],
  BOOKING_SESSION_FLOW: ['@flow:booking-session-flow', '@module:booking', '@priority:P1'],
  BOOKING_COMPLETE_FLOW: ['@flow:booking-complete-flow', '@module:booking', '@priority:P1'],
  BOOKING_ERROR_PATHS: ['@flow:booking-error-paths', '@module:booking', '@priority:P2'],
  BOOKING_RESCHEDULE: ['@flow:booking-reschedule', '@module:booking', '@priority:P2'],
  BOOKING_CALENDAR_REDIRECT: ['@flow:booking-calendar-redirect', '@module:booking', '@priority:P2'],
  BOOKING_CALENDAR_EDGE_CASES: ['@flow:booking-calendar-edge-cases', '@module:booking', '@priority:P3'],
  BOOKING_NO_SESSIONS: ['@flow:booking-no-sessions', '@module:booking', '@priority:P2'],
  BOOKING_SESSION_DETAIL: ['@flow:booking-session-detail', '@module:booking', '@priority:P2'],
  BOOKING_CANCEL_FLOW: ['@flow:booking-cancel-flow', '@module:booking', '@priority:P1'],

  APP_COVERAGE_GAPS: ['@flow:app-coverage-gaps', '@module:app', '@priority:P3'],
  APP_EDGE_CASE_BRANCHES: ['@flow:app-edge-case-branches', '@module:app', '@priority:P3'],
  APP_STORE_ERROR_PATHS: ['@flow:app-store-error-paths', '@module:app', '@priority:P3'],
  APP_SIDEBAR_NAVIGATION: ['@flow:app-sidebar-navigation', '@module:navigation', '@priority:P3'],
  MOBILE_BOTTOM_NAV: ['@flow:mobile-bottom-nav', '@module:navigation', '@priority:P2'],
  TRAINER_MOBILE_BOTTOM_NAV: ['@flow:trainer-mobile-bottom-nav', '@module:navigation', '@priority:P3'],

  DASHBOARD_OVERVIEW: ['@flow:dashboard-overview', '@module:dashboard', '@priority:P1'],
  CUSTOMER_CREDITS: ['@flow:customer-credits', '@module:app', '@priority:P2'],
  CUSTOMER_STORE: ['@flow:customer-store', '@module:app', '@priority:P2'],
  CUSTOMER_SESSION_GRANTS: ['@flow:customer-session-grants', '@module:app', '@priority:P2'],
  TRAINER_STORE_MANAGEMENT: ['@flow:trainer-store-management', '@module:trainer', '@priority:P2'],
  DASHBOARD_REMINDER: ['@flow:dashboard-reminder', '@module:dashboard', '@priority:P2'],

  MY_PROGRAMS_LIST: ['@flow:my-programs-list', '@module:programs', '@priority:P1'],
  MY_PROGRAMS_DETAIL: ['@flow:my-programs-detail', '@module:programs', '@priority:P2'],

  SUBSCRIPTION_PAGE: ['@flow:subscription-page', '@module:subscription', '@priority:P1'],
  SUBSCRIPTION_EXPIRY_REMINDER: ['@flow:subscription-expiry-reminder', '@module:subscription', '@priority:P2'],
  SUBSCRIPTION_CANCEL_FLOW: ['@flow:subscription-cancel-flow', '@module:subscription', '@priority:P2'],
  SUBSCRIPTION_BILLING_FAILED_RECOVERY: ['@flow:subscription-billing-failed-recovery', '@module:subscription', '@priority:P2'],
  SUBSCRIPTION_GATED_ROUTES: ['@flow:subscription-gated-routes', '@module:subscription', '@priority:P2'],

  CHECKOUT_FLOW: ['@flow:checkout-flow', '@module:checkout', '@priority:P1'],
  CHECKOUT_GUEST_REDIRECT: ['@flow:checkout-guest-redirect', '@module:checkout', '@priority:P2'],
  CHECKOUT_COVERAGE_GAPS: ['@flow:checkout-coverage-gaps', '@module:checkout', '@priority:P3'],
  CHECKOUT_PAYMENT_STATUS_POLLING: ['@flow:checkout-payment-status-polling', '@module:checkout', '@priority:P2'],

  PUBLIC_HOME: ['@flow:public-home', '@module:public', '@priority:P2'],
  PUBLIC_NAVBAR: ['@flow:public-navbar', '@module:public', '@priority:P3'],
  PUBLIC_BRAND: ['@flow:public-brand', '@module:public', '@priority:P3'],
  PUBLIC_PROGRAMS: ['@flow:public-programs', '@module:programs', '@priority:P2'],
  PUBLIC_CONTACT: ['@flow:public-contact', '@module:public', '@priority:P3'],
  PUBLIC_FAQ: ['@flow:public-faq', '@module:public', '@priority:P3'],
  PUBLIC_FAQ_ERRORS: ['@flow:public-faq-errors', '@module:public', '@priority:P3'],
  PUBLIC_TERMS: ['@flow:public-terms', '@module:public', '@priority:P3'],
  PUBLIC_WHATSAPP_CTA: ['@flow:public-whatsapp-cta', '@module:public', '@priority:P4'],

  AUTH_FORGOT_PASSWORD: ['@flow:auth-forgot-password', '@module:auth', '@priority:P1'],

  PROFILE_MANAGEMENT: ['@flow:profile-management', '@module:profile', '@priority:P1'],
  PROFILE_PASSWORD_CHANGE: ['@flow:profile-password-change', '@module:profile', '@priority:P2'],
  PROFILE_MOOD_ENTRY: ['@flow:profile-mood-entry', '@module:profile', '@priority:P3'],
  PROFILE_COMPLETION_CTA: ['@flow:profile-completion-cta', '@module:profile', '@priority:P2'],

  CUSTOMER_DIAGNOSIS: ['@flow:customer-diagnosis', '@module:assessments', '@priority:P2'],
  CUSTOMER_NUTRITION: ['@flow:customer-nutrition', '@module:assessments', '@priority:P2'],
  CUSTOMER_PARQ: ['@flow:customer-parq', '@module:assessments', '@priority:P2'],
  CUSTOMER_PHYSICAL_EVALUATION: ['@flow:customer-physical-evaluation', '@module:assessments', '@priority:P2'],
  CUSTOMER_POSTUROMETRY: ['@flow:customer-posturometry', '@module:assessments', '@priority:P2'],
  CUSTOMER_PENDING_ASSESSMENTS: ['@flow:customer-pending-assessments', '@module:assessments', '@priority:P3'],

  TRAINER_DASHBOARD: ['@flow:trainer-dashboard', '@module:trainer', '@priority:P1'],
  TRAINER_CLIENTS_LIST: ['@flow:trainer-clients-list', '@module:trainer', '@priority:P1'],
  TRAINER_CLIENT_DETAIL: ['@flow:trainer-client-detail', '@module:trainer', '@priority:P1'],
  TRAINER_CLIENT_ANTHROPOMETRY: ['@flow:trainer-client-anthropometry', '@module:trainer', '@priority:P2'],
  TRAINER_CLIENT_NUTRITION: ['@flow:trainer-client-nutrition', '@module:trainer', '@priority:P2'],
  TRAINER_CLIENT_PARQ: ['@flow:trainer-client-parq', '@module:trainer', '@priority:P2'],
  TRAINER_CLIENT_PHYSICAL_EVAL: ['@flow:trainer-client-physical-eval', '@module:trainer', '@priority:P2'],
  TRAINER_CLIENT_PHYSICAL_TESTS: ['@flow:trainer-client-physical-tests', '@module:trainer', '@priority:P2'],
  TRAINER_CLIENT_POSTUROMETRY: ['@flow:trainer-client-posturometry', '@module:trainer', '@priority:P2'],
  TRAINER_ALERTS: ['@flow:trainer-alerts', '@module:trainer', '@priority:P1'],
  TRAINER_CLIENT_PROGRAM: ['@flow:trainer-client-program', '@module:trainer', '@priority:P2'],
  TRAINER_CLIENT_NOTES: ['@flow:trainer-client-notes', '@module:trainer', '@priority:P2'],
  TRAINER_METRICS: ['@flow:trainer-metrics', '@module:trainer', '@priority:P3'],
  TRAINER_NUTRITION_CATALOG: ['@flow:trainer-nutrition-catalog', '@module:trainer', '@priority:P2'],

  CUSTOMER_MI_PROGRAMA: ['@flow:customer-mi-programa', '@module:program', '@priority:P1'],
  CUSTOMER_MI_PROGRAMA_RUTINA: ['@flow:customer-mi-programa-rutina', '@module:program', '@priority:P1'],
  PROGRAM_WORKOUT_CAPTURES: ['@flow:program-workout-captures', '@module:program', '@priority:P2'],
  CUSTOMER_MI_PROGRAMA_PROGRESO: ['@flow:customer-mi-programa-progreso', '@module:program', '@priority:P2'],
  CUSTOMER_MI_PROGRAMA_RESUMEN: ['@flow:customer-mi-programa-resumen', '@module:program', '@priority:P2'],
  CUSTOMER_MI_PROGRAMA_DIA: ['@flow:customer-mi-programa-dia', '@module:program', '@priority:P2'],

  AUTH_ACCEPT_INVITE: ['@flow:auth-accept-invite', '@module:auth', '@priority:P2'],
  AUTH_FORCED_PASSWORD_CHANGE: ['@flow:auth-forced-password-change', '@module:auth', '@priority:P2'],

  ADMIN_DASHBOARD: ['@flow:admin-dashboard', '@module:admin', '@priority:P2'],
  ADMIN_USERS_LIST: ['@flow:admin-users-list', '@module:admin', '@priority:P1'],
  ADMIN_USER_CREATE: ['@flow:admin-user-create', '@module:admin', '@priority:P1'],
  ADMIN_USER_DETAIL: ['@flow:admin-user-detail', '@module:admin', '@priority:P1'],
  ADMIN_SUBSCRIPTIONS_LIST: ['@flow:admin-subscriptions-list', '@module:admin', '@priority:P2'],
  ADMIN_SUBSCRIPTION_CREATE: ['@flow:admin-subscription-create', '@module:admin', '@priority:P1'],
  ADMIN_SUBSCRIPTION_DETAIL: ['@flow:admin-subscription-detail', '@module:admin', '@priority:P1'],
  ADMIN_PLANS: ['@flow:admin-plans', '@module:admin', '@priority:P1'],

  CUSTOMER_NUTRITION_DAILY: ['@flow:customer-nutrition-daily', '@module:nutrition', '@priority:P2'],
  CUSTOMER_NUTRITION_PLAN: ['@flow:customer-nutrition-plan', '@module:nutrition', '@priority:P2'],
  SUBSCRIPTION_DUO_INVITE: ['@flow:subscription-duo-invite', '@module:subscription', '@priority:P2'],

  TRAINER_CLIENT_NUTRITION_PLAN: ['@flow:trainer-client-nutrition-plan', '@module:trainer', '@priority:P2'],
  TRAINER_CLIENT_BOOKING: ['@flow:trainer-client-booking', '@module:trainer', '@priority:P2'],
  TRAINER_CLIENT_MESSAGING: ['@flow:trainer-client-messaging', '@module:trainer', '@priority:P2'],
  CUSTOMER_TRAINER_MESSAGE: ['@flow:customer-trainer-message', '@module:dashboard', '@priority:P3'],
};

export const RoleTags = {
  GUEST: '@role:guest',
  USER: '@role:user',
  TRAINER: '@role:trainer',
  ADMIN: '@role:admin',
};
