"""
Seed ~170 Colombian meal suggestions organized by meal_block, goal, and fitness level.
Idempotent — re-running updates existing records.

Run: python manage.py seed_meal_suggestions
"""
from django.core.management.base import BaseCommand

from core_app.models import MealSuggestion

SUGGESTIONS = [
    # ═══ DESAYUNO ═══════════════════════════════════════════════════════════════
    # --- general_health ---
    dict(title='Arepa con huevo y aguacate', meal_block='desayuno', calories_estimate=380,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=5,
         description='Arepa de maíz con huevo revuelto y media porción de aguacate'),
    dict(title='Calentado paisa', meal_block='desayuno', calories_estimate=450,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=3,
         description='Arroz, frijoles y huevo frito del día anterior'),
    dict(title='Changua con huevo', meal_block='desayuno', calories_estimate=290,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Caldo de leche con cebolla, huevo pochado y cilantro'),
    dict(title='Avena con leche y banano', meal_block='desayuno', calories_estimate=350,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Avena en leche con banano en rodajas'),
    dict(title='Tostadas integrales con queso y tomate', meal_block='desayuno', calories_estimate=320,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Pan integral tostado con queso campesino y tomate'),
    dict(title='Huevos pericos con arepa', meal_block='desayuno', calories_estimate=400,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=5,
         description='Huevos revueltos con tomate y cebolla, acompañados de arepa'),
    dict(title='Yogur natural con granola y fresas', meal_block='desayuno', calories_estimate=300,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Yogur natural con granola casera y fresas frescas'),
    dict(title='Caldo de costilla con papa', meal_block='desayuno', calories_estimate=260,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Caldo tradicional bogotano con papa criolla y cilantro'),
    dict(title='Arepa con quesillo y hogao', meal_block='desayuno', calories_estimate=410,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=4,
         description='Arepa paisa con quesillo derretido y hogao de tomate y cebolla'),
    dict(title='Smoothie de mango con avena', meal_block='desayuno', calories_estimate=280,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Batido de mango maduro con avena y leche descremada'),
    # --- fat_loss ---
    dict(title='Claras de huevo con espinaca y arepa pequeña', meal_block='desayuno', calories_estimate=240,
         goal_tags=['fat_loss'], fitness_level_min=2, fitness_level_max=5,
         description='4 claras de huevo salteadas con espinaca y 1 arepa pequeña'),
    dict(title='Frutas frescas con yogur griego', meal_block='desayuno', calories_estimate=220,
         goal_tags=['fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Papaya, piña y mango con yogur griego sin azúcar'),
    dict(title='Avena con proteína y frutos rojos', meal_block='desayuno', calories_estimate=310,
         goal_tags=['fat_loss', 'muscle_gain'], fitness_level_min=3, fitness_level_max=5,
         description='Avena cocida con proteína en polvo y moras o fresas'),
    dict(title='Tostadas de yuca con aguacate y huevo', meal_block='desayuno', calories_estimate=360,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Rodajas de yuca cocida tostadas, con aguacate y huevo pochado'),
    # --- muscle_gain ---
    dict(title='Arepa rellena de pollo y queso', meal_block='desayuno', calories_estimate=520,
         goal_tags=['muscle_gain'], fitness_level_min=3, fitness_level_max=5,
         description='Arepa de choclo rellena de pollo desmechado y queso'),
    dict(title='Batido de leche con banano y maní', meal_block='desayuno', calories_estimate=480,
         goal_tags=['muscle_gain'], fitness_level_min=3, fitness_level_max=5,
         description='Leche entera batida con banano y 2 cucharadas de mantequilla de maní'),
    dict(title='Huevos revueltos con 3 proteínas', meal_block='desayuno', calories_estimate=500,
         goal_tags=['muscle_gain'], fitness_level_min=4, fitness_level_max=5,
         description='3 huevos enteros + 2 claras con jamón, queso y pimentón'),
    dict(title='Calentado con proteína extra', meal_block='desayuno', calories_estimate=560,
         goal_tags=['muscle_gain'], fitness_level_min=3, fitness_level_max=5,
         description='Calentado paisa con pechuga de pollo adicional'),

    # ═══ MEDIA MAÑANA ════════════════════════════════════════════════════════════
    dict(title='Mango y maracuyá frescos', meal_block='media_manana', calories_estimate=120,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Porción de mango maduro con jugo de maracuyá'),
    dict(title='Banano con maní', meal_block='media_manana', calories_estimate=200,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=5,
         description='1 banano mediano con una cucharada de maní tostado'),
    dict(title='Guanábana en trozos', meal_block='media_manana', calories_estimate=100,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Porción de guanábana fresca'),
    dict(title='Yogur griego con papaya', meal_block='media_manana', calories_estimate=160,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Yogur griego sin azúcar con trozos de papaya'),
    dict(title='Frutos secos y semillas', meal_block='media_manana', calories_estimate=180,
         goal_tags=['general_health', 'fat_loss', 'muscle_gain'], fitness_level_min=2, fitness_level_max=5,
         description='Mix de almendras, nueces y semillas de girasol'),
    dict(title='Batido de mora con leche', meal_block='media_manana', calories_estimate=190,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Batido de moras con leche y una pizca de panela'),
    dict(title='Arepa pequeña con queso', meal_block='media_manana', calories_estimate=220,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=4,
         description='Arepa pequeña con queso campesino'),
    dict(title='Fruta de temporada', meal_block='media_manana', calories_estimate=100,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Porción de fruta de temporada: lulo, pitahaya o uchuva'),
    dict(title='Barra de avena y miel casera', meal_block='media_manana', calories_estimate=210,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=5,
         description='Barra casera de avena, miel y semillas'),
    dict(title='Proteína con agua y fruta', meal_block='media_manana', calories_estimate=170,
         goal_tags=['fat_loss', 'muscle_gain'], fitness_level_min=3, fitness_level_max=5,
         description='Shake de proteína con agua más una fruta de temporada'),
    dict(title='Tostada integral con mermelada sin azúcar', meal_block='media_manana', calories_estimate=140,
         goal_tags=['fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Pan integral con mermelada de fruta sin azúcar añadida'),

    # ═══ ALMUERZO ════════════════════════════════════════════════════════════════
    # --- general_health ---
    dict(title='Sancocho de pollo con arroz', meal_block='almuerzo', calories_estimate=520,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Sancocho de pollo con papa, yuca, mazorca y arroz blanco'),
    dict(title='Arroz con pollo y ensalada', meal_block='almuerzo', calories_estimate=480,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Arroz con pollo en salsa de tomate y ensalada mixta'),
    dict(title='Frijoles con arroz y carne', meal_block='almuerzo', calories_estimate=550,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=5,
         description='Frijoles rojos con hogao, arroz, carne molida y aguacate'),
    dict(title='Sopa de lentejas con pollo', meal_block='almuerzo', calories_estimate=420,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Sopa de lentejas con pechuga de pollo desmenuzada y verduras'),
    dict(title='Bandeja paisa moderada', meal_block='almuerzo', calories_estimate=700,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=3,
         description='Porción moderada de bandeja paisa: frijoles, arroz, chicharrón, huevo, arepa'),
    dict(title='Pechugas de pollo a la plancha con arroz integral', meal_block='almuerzo', calories_estimate=440,
         goal_tags=['general_health', 'fat_loss', 'muscle_gain'], fitness_level_min=2, fitness_level_max=5,
         description='Pechuga de pollo a la plancha con arroz integral y vegetales al vapor'),
    dict(title='Sopa de papa con costilla', meal_block='almuerzo', calories_estimate=390,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Sopa espesa de papa criolla con costilla de res y cilantro'),
    dict(title='Cazuela de mariscos con arroz', meal_block='almuerzo', calories_estimate=490,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=2, fitness_level_max=5,
         description='Cazuela costeña con camarones, pescado y arroz con coco'),
    dict(title='Ajiaco bogotano', meal_block='almuerzo', calories_estimate=430,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Ajiaco con tres tipos de papa, pollo, mazorca y crema'),
    dict(title='Sudado de pollo con papa', meal_block='almuerzo', calories_estimate=460,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Pollo sudado en hogao con papa amarilla y arroz'),
    dict(title='Arroz con atún y vegetales', meal_block='almuerzo', calories_estimate=410,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Arroz con atún en agua, tomate, pimentón y pepino'),
    dict(title='Sopa de arveja con carne', meal_block='almuerzo', calories_estimate=400,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Sopa de arvejas partidas con carne de res y papa'),
    # --- fat_loss ---
    dict(title='Ensalada de pollo con aguacate', meal_block='almuerzo', calories_estimate=340,
         goal_tags=['fat_loss'], fitness_level_min=2, fitness_level_max=5,
         description='Pollo a la plancha sobre ensalada de hojas verdes con aguacate y limón'),
    dict(title='Tilapia al vapor con ensalada', meal_block='almuerzo', calories_estimate=310,
         goal_tags=['fat_loss'], fitness_level_min=2, fitness_level_max=5,
         description='Filete de tilapia al vapor con ensalada de pepino, tomate y cilantro'),
    dict(title='Sopa de verduras con pollo', meal_block='almuerzo', calories_estimate=290,
         goal_tags=['fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Sopa de verduras de temporada con trozos de pechuga y papa mínima'),
    dict(title='Wrap de lechuga con pollo y vegetales', meal_block='almuerzo', calories_estimate=280,
         goal_tags=['fat_loss'], fitness_level_min=3, fitness_level_max=5,
         description='Hojas de lechuga rellenas de pollo, zanahoria, pepino y salsa de yogur'),
    dict(title='Quinua con verduras y huevo', meal_block='almuerzo', calories_estimate=360,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=3, fitness_level_max=5,
         description='Quinua cocida con vegetales salteados y huevo pochado'),
    # --- muscle_gain ---
    dict(title='Arroz integral con carne molida y frijoles', meal_block='almuerzo', calories_estimate=620,
         goal_tags=['muscle_gain'], fitness_level_min=3, fitness_level_max=5,
         description='Arroz integral, carne molida de res, frijoles y plátano maduro'),
    dict(title='Pollo entero al horno con papa y ensalada', meal_block='almuerzo', calories_estimate=680,
         goal_tags=['muscle_gain'], fitness_level_min=4, fitness_level_max=5,
         description='Pechuga y muslo de pollo horneados con papa y ensalada grande'),
    dict(title='Carne asada con arroz y lentejas', meal_block='almuerzo', calories_estimate=650,
         goal_tags=['muscle_gain'], fitness_level_min=3, fitness_level_max=5,
         description='Lomo de res a la parrilla con arroz, lentejas y aguacate'),
    dict(title='Pasta integral con pollo y brócoli', meal_block='almuerzo', calories_estimate=590,
         goal_tags=['muscle_gain', 'general_health'], fitness_level_min=3, fitness_level_max=5,
         description='Pasta integral con pechuga de pollo, brócoli y salsa de tomate'),

    # ═══ MERIENDA ════════════════════════════════════════════════════════════════
    dict(title='Maní con banano', meal_block='merienda', calories_estimate=210,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=5,
         description='Porción de maní tostado sin sal con un banano'),
    dict(title='Avena con leche y canela', meal_block='merienda', calories_estimate=200,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Avena en leche tibia con canela y una pizca de panela'),
    dict(title='Yogur natural con mango', meal_block='merienda', calories_estimate=170,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Yogur natural con trozos de mango fresco'),
    dict(title='Proteína con leche o agua', meal_block='merienda', calories_estimate=160,
         goal_tags=['fat_loss', 'muscle_gain'], fitness_level_min=3, fitness_level_max=5,
         description='Shake de proteína de suero después del entrenamiento'),
    dict(title='Pitahaya con yogur griego', meal_block='merienda', calories_estimate=140,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Pitahaya amarilla pelada con yogur griego'),
    dict(title='Uchuvas y almendras', meal_block='merienda', calories_estimate=160,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Porción de uchuvas frescas con 10 almendras'),
    dict(title='Arepa pequeña con queso y café', meal_block='merienda', calories_estimate=260,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Arepa pequeña con queso blanco y tinto o aromática'),
    dict(title='Batido de frutas sin azúcar', meal_block='merienda', calories_estimate=150,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Batido de mora o fresa con leche descremada sin azúcar'),
    dict(title='Tostadas con hummus de garbanzo', meal_block='merienda', calories_estimate=190,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=2, fitness_level_max=5,
         description='Tostadas de pan integral con hummus casero'),
    dict(title='Fruta de temporada con sal y limón', meal_block='merienda', calories_estimate=90,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Mango, sandía o piña con un toque de sal y limón'),
    dict(title='Nueces con fruta seca', meal_block='merienda', calories_estimate=200,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=2, fitness_level_max=5,
         description='Mix de nueces y pasas o arándanos secos'),

    # ═══ CENA ════════════════════════════════════════════════════════════════════
    # --- general_health ---
    dict(title='Caldo de pollo con verduras', meal_block='cena', calories_estimate=220,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Caldo liviano de pollo con zanahoria, apio, papa y cilantro'),
    dict(title='Arepa con queso y chocolate', meal_block='cena', calories_estimate=380,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Arepa con quesillo y chocolatina o bebida de chocolate'),
    dict(title='Sopa de fideo con pollo', meal_block='cena', calories_estimate=300,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Sopa de fideos con pollo desmenuzado y papa'),
    dict(title='Ensalada de atún con aguacate', meal_block='cena', calories_estimate=310,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Atún en agua con aguacate, tomate y limón'),
    dict(title='Plátano maduro con queso', meal_block='cena', calories_estimate=320,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Plátano maduro horneado o frito con queso campesino'),
    dict(title='Sopa de quinua con vegetales', meal_block='cena', calories_estimate=280,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=2, fitness_level_max=5,
         description='Sopa de quinua con zanahoria, apio y espinaca'),
    dict(title='Pollo a la plancha con ensalada nocturna', meal_block='cena', calories_estimate=350,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=2, fitness_level_max=5,
         description='Pechuga de pollo a la plancha con ensalada de aguacate y tomate'),
    dict(title='Crema de ahuyama', meal_block='cena', calories_estimate=200,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Crema suave de ahuyama (zapallo) con un toque de leche de coco'),
    dict(title='Empanadas de pipián horneadas', meal_block='cena', calories_estimate=360,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='2 empanadas de maíz rellenas de pipián (papas y maní) horneadas'),
    dict(title='Huevos cocidos con ensalada', meal_block='cena', calories_estimate=260,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='2 huevos cocidos con ensalada de pepino, lechuga y zanahoria'),
    # --- fat_loss ---
    dict(title='Caldo de verduras sin grasa', meal_block='cena', calories_estimate=120,
         goal_tags=['fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Caldo de vegetales con apio, zanahoria, espinaca y cúrcuma'),
    dict(title='Pescado al vapor con brócoli', meal_block='cena', calories_estimate=280,
         goal_tags=['fat_loss'], fitness_level_min=2, fitness_level_max=5,
         description='Filete de tilapia o mojarra al vapor con brócoli y limón'),
    dict(title='Ensalada proteica nocturna', meal_block='cena', calories_estimate=300,
         goal_tags=['fat_loss'], fitness_level_min=3, fitness_level_max=5,
         description='Atún, claras de huevo cocidas, lechuga, tomate y vinagreta de limón'),
    dict(title='Sopa de espinaca con huevo', meal_block='cena', calories_estimate=190,
         goal_tags=['fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Sopa ligera de espinaca con huevo pochado'),
    # --- muscle_gain ---
    dict(title='Arroz con carne y plátano maduro', meal_block='cena', calories_estimate=580,
         goal_tags=['muscle_gain'], fitness_level_min=3, fitness_level_max=5,
         description='Arroz blanco con bistec de res y plátano maduro frito'),
    dict(title='Pasta con atún y tomate', meal_block='cena', calories_estimate=520,
         goal_tags=['muscle_gain', 'general_health'], fitness_level_min=3, fitness_level_max=5,
         description='Pasta con atún, salsa de tomate y aceite de oliva'),
    dict(title='Pollo horneado con papa y ensalada', meal_block='cena', calories_estimate=550,
         goal_tags=['muscle_gain'], fitness_level_min=4, fitness_level_max=5,
         description='Muslo de pollo horneado con papa cocida y ensalada verde'),
    dict(title='Shake nocturno de proteína con maní', meal_block='cena', calories_estimate=380,
         goal_tags=['muscle_gain'], fitness_level_min=4, fitness_level_max=5,
         description='Proteína de caseína con leche y mantequilla de maní antes de dormir'),

    # ═══ DESAYUNO — adicionales ══════════════════════════════════════════════════
    dict(title='Tamal tolimense', meal_block='desayuno', calories_estimate=490,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=3,
         description='Tamal de maíz con pollo, cerdo, arveja y zanahoria'),
    dict(title='Pandebono con café', meal_block='desayuno', calories_estimate=310,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Pan de bono recién hecho con tinto o agua de panela'),
    dict(title='Colada de maíz con leche', meal_block='desayuno', calories_estimate=290,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Colada tradicional de maíz con leche y canela'),
    dict(title='Arepa de choclo con mantequilla', meal_block='desayuno', calories_estimate=350,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=5,
         description='Arepa de choclo dulce con mantequilla y sal'),
    dict(title='Huevos tibios con tostadas y zumo de naranja', meal_block='desayuno', calories_estimate=370,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='2 huevos tibios, 2 tostadas de pan integral y jugo de naranja natural'),
    dict(title='Cereal integral con leche y fruta', meal_block='desayuno', calories_estimate=330,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Cereal de avena o granola con leche descremada y fruta picada'),
    dict(title='Obleas con arequipe y frutas', meal_block='desayuno', calories_estimate=300,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=3,
         description='Oblea con arequipe, queso y frutas frescas'),
    dict(title='Peto de maíz', meal_block='desayuno', calories_estimate=250,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Bebida tradicional de maíz tierno cocido con leche y azúcar mínimo'),
    dict(title='Tostadas con aguacate y huevo pochado', meal_block='desayuno', calories_estimate=390,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=2, fitness_level_max=5,
         description='Pan integral tostado con aguacate triturado y huevo pochado encima'),
    dict(title='Omelet de vegetales con arepa', meal_block='desayuno', calories_estimate=410,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=2, fitness_level_max=5,
         description='Omelet de 3 huevos con espinaca, tomate y pimentón, con arepa'),
    dict(title='Salpicón de frutas con leche', meal_block='desayuno', calories_estimate=240,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Mezcla de frutas tropicales picadas con leche y bolas de helado de leche'),
    dict(title='Avena con chontaduro', meal_block='desayuno', calories_estimate=360,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=5,
         description='Avena en leche con chontaduro cocido y miel de abejas'),

    # ═══ MEDIA MAÑANA — adicionales ══════════════════════════════════════════════
    dict(title='Chontaduro con sal y limón', meal_block='media_manana', calories_estimate=130,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Chontaduro cocido con sal de ajo y jugo de limón'),
    dict(title='Lulo en jugo sin azúcar', meal_block='media_manana', calories_estimate=70,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Jugo de lulo natural sin azúcar con agua'),
    dict(title='Tostadas de arroz con mantequilla de maní', meal_block='media_manana', calories_estimate=190,
         goal_tags=['muscle_gain', 'general_health'], fitness_level_min=2, fitness_level_max=5,
         description='Galletas de arroz con mantequilla de maní natural'),
    dict(title='Ensalada de frutas tropicales', meal_block='media_manana', calories_estimate=130,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Mix de mango, piña, papaya y maracuyá sin azúcar'),
    dict(title='Queso campesino con papayuela', meal_block='media_manana', calories_estimate=160,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Trozo de queso blanco con papayuela en almíbar ligero'),
    dict(title='Mazamorra con panela', meal_block='media_manana', calories_estimate=200,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Maíz cocido en agua con panela raspada'),
    dict(title='Aguapanela con limón', meal_block='media_manana', calories_estimate=80,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Bebida tradicional de panela con limón, tibia o fría'),
    dict(title='Granola con leche y pitahaya', meal_block='media_manana', calories_estimate=220,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Granola de avena con leche y pitahaya amarilla'),
    dict(title='Huevo cocido solo', meal_block='media_manana', calories_estimate=90,
         goal_tags=['fat_loss', 'muscle_gain'], fitness_level_min=1, fitness_level_max=5,
         description='1 huevo cocido duro, opción proteica rápida'),

    # ═══ ALMUERZO — adicionales ══════════════════════════════════════════════════
    dict(title='Mojarra frita con arroz y patacones', meal_block='almuerzo', calories_estimate=580,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=4,
         description='Mojarra frita entera con arroz blanco y patacones'),
    dict(title='Carne en bisté con papas criollas', meal_block='almuerzo', calories_estimate=510,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=2, fitness_level_max=5,
         description='Bistec de res sudado con papas criollas y ensalada'),
    dict(title='Sopa de mondongo con arroz', meal_block='almuerzo', calories_estimate=470,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=3,
         description='Mondongo bogotano con garbanzos, papa y arroz'),
    dict(title='Pollo al ajillo con arroz y aguacate', meal_block='almuerzo', calories_estimate=500,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=2, fitness_level_max=5,
         description='Pollo al ajillo en aceite de oliva con arroz y aguacate'),
    dict(title='Sopa de arveja con cerdo', meal_block='almuerzo', calories_estimate=420,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=4,
         description='Sopa espesa de arvejas con costilla de cerdo y papa'),
    dict(title='Arroz con camarón y coco', meal_block='almuerzo', calories_estimate=540,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=2, fitness_level_max=5,
         description='Arroz con leche de coco y camarones, estilo costeño'),
    dict(title='Pepitoria de cuy', meal_block='almuerzo', calories_estimate=450,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=2, fitness_level_max=5,
         description='Preparación tradicional nariñense de cuy con papas y salsa'),
    dict(title='Ensalada de garbanzo con atún', meal_block='almuerzo', calories_estimate=380,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=2, fitness_level_max=5,
         description='Garbanzos cocidos con atún, tomate, pepino y vinagreta'),
    dict(title='Cocido boyacense', meal_block='almuerzo', calories_estimate=560,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=3,
         description='Puchero boyacense con papa, mazorca, arveja, carne y chicharrón'),
    dict(title='Tilapia a la plancha con yuca y ensalada', meal_block='almuerzo', calories_estimate=430,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=2, fitness_level_max=5,
         description='Tilapia a la plancha con yuca cocida y ensalada de repollo'),
    dict(title='Lentejas con chorizo y arroz', meal_block='almuerzo', calories_estimate=490,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=4,
         description='Guiso de lentejas con chorizo, papa y arroz blanco'),
    dict(title='Wrap de pollo con vegetales asados', meal_block='almuerzo', calories_estimate=420,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=3, fitness_level_max=5,
         description='Tortilla integral con pollo, pimentón asado y lechuga'),
    dict(title='Sopa de frijol antiqueño', meal_block='almuerzo', calories_estimate=440,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Sopa de frijol cargamanto con costilla, papa, plátano y cilantro'),
    dict(title='Ceviche de camarón con patacones', meal_block='almuerzo', calories_estimate=390,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=2, fitness_level_max=5,
         description='Ceviche de camarones con limón, cebolla y cilantro, con patacones'),
    dict(title='Bowl de arroz integral con salmón y aguacate', meal_block='almuerzo', calories_estimate=520,
         goal_tags=['muscle_gain', 'fat_loss'], fitness_level_min=4, fitness_level_max=5,
         description='Bowl de arroz integral con salmón al horno, aguacate y semillas'),
    dict(title='Pechuga rellena con espinaca y queso', meal_block='almuerzo', calories_estimate=460,
         goal_tags=['muscle_gain', 'fat_loss'], fitness_level_min=4, fitness_level_max=5,
         description='Pechuga de pollo rellena de espinaca y queso bajo en grasa'),
    dict(title='Estofado de res con papa y zanahoria', meal_block='almuerzo', calories_estimate=490,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=2, fitness_level_max=5,
         description='Carne de res en estofado con papa, zanahoria y caldo'),
    dict(title='Arroz con coles de bruselas y pollo', meal_block='almuerzo', calories_estimate=440,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=3, fitness_level_max=5,
         description='Arroz integral con coles de Bruselas salteadas y pollo desmechado'),
    dict(title='Sopa de champiñones con papa', meal_block='almuerzo', calories_estimate=280,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Crema de champiñones con papa y cebolla larga'),

    # ═══ MERIENDA — adicionales ══════════════════════════════════════════════════
    dict(title='Pandequeso', meal_block='merienda', calories_estimate=230,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Pandequeso recién hecho acompañado de aromática'),
    dict(title='Agua de panela con limón', meal_block='merienda', calories_estimate=80,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Bebida tradicional de panela con limón para reponer energía'),
    dict(title='Chontaduro con miel', meal_block='merienda', calories_estimate=160,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=5,
         description='Chontaduro cocido con miel de abejas, rico en carbohidratos complejos'),
    dict(title='Mezcla de frutas secas', meal_block='merienda', calories_estimate=190,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=2, fitness_level_max=5,
         description='Mix de higos secos, ciruela pasa y dátiles'),
    dict(title='Avena fría con cacao sin azúcar', meal_block='merienda', calories_estimate=180,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=2, fitness_level_max=5,
         description='Overnight oats con cacao en polvo sin azúcar y leche descremada'),
    dict(title='Zanahoria con hummus', meal_block='merienda', calories_estimate=130,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Bastones de zanahoria con hummus de garbanzo'),
    dict(title='Mini arepa con hogao', meal_block='merienda', calories_estimate=200,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Arepa pequeña con hogao casero de tomate y cebolla'),
    dict(title='Shake de proteína con avena', meal_block='merienda', calories_estimate=250,
         goal_tags=['muscle_gain'], fitness_level_min=3, fitness_level_max=5,
         description='Proteína de suero mezclada con avena y agua o leche'),

    # ═══ CENA — adicionales ══════════════════════════════════════════════════════
    dict(title='Mazamorra de leche', meal_block='cena', calories_estimate=250,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Maíz pelado cocido en leche con un toque de panela'),
    dict(title='Sopa de pasta con pollo y zanahoria', meal_block='cena', calories_estimate=320,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Sopa de pasta corta con pollo, zanahoria y papa'),
    dict(title='Arepas con hogao y aguacate', meal_block='cena', calories_estimate=360,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Dos arepas con hogao de tomate, cebolla y aguacate'),
    dict(title='Caldo de costilla liviano', meal_block='cena', calories_estimate=180,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Caldo desgrasado de costilla con papa y cilantro'),
    dict(title='Ensalada de repollo morado con atún', meal_block='cena', calories_estimate=280,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Repollo morado, zanahoria y atún con vinagreta de limón'),
    dict(title='Sopa de crema de espárragos', meal_block='cena', calories_estimate=190,
         goal_tags=['fat_loss'], fitness_level_min=2, fitness_level_max=5,
         description='Crema ligera de espárragos con leche descremada y nuez moscada'),
    dict(title='Revuelto de huevo con champiñones', meal_block='cena', calories_estimate=270,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='2 huevos revueltos con champiñones, espinaca y tomate cherry'),
    dict(title='Sancocho ligero de pollo', meal_block='cena', calories_estimate=310,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Sancocho de pechuga con yuca, mazorca y verduras, poca papa'),
    dict(title='Bowl de carne molida con papas y ensalada', meal_block='cena', calories_estimate=490,
         goal_tags=['muscle_gain'], fitness_level_min=3, fitness_level_max=5,
         description='Carne molida de res salteada con papas y ensalada verde'),
    dict(title='Plátano verde con queso y hogao', meal_block='cena', calories_estimate=330,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Patacón de plátano verde con queso fundido y hogao'),
    dict(title='Sopa de tortilla de maíz', meal_block='cena', calories_estimate=270,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Caldo de pollo con tiras de tortilla de maíz y aguacate'),
    dict(title='Carne desmechada con yuca y ensalada', meal_block='cena', calories_estimate=440,
         goal_tags=['muscle_gain', 'general_health'], fitness_level_min=3, fitness_level_max=5,
         description='Res desmechada con yuca cocida y ensalada de pepino'),
    dict(title='Pechuga de pavo con ensalada tibia', meal_block='cena', calories_estimate=340,
         goal_tags=['fat_loss', 'muscle_gain'], fitness_level_min=3, fitness_level_max=5,
         description='Filete de pavo a la plancha con ensalada de espinaca tibia y tomate'),

    # ═══ Relleno para llegar a 150 ═══════════════════════════════════════════════
    dict(title='Arepa boyacense con papa y chicharrón', meal_block='desayuno', calories_estimate=430,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=3,
         description='Arepa boyacense de maíz con papa y chicharrón'),
    dict(title='Guanábana con leche de coco', meal_block='media_manana', calories_estimate=150,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Pulpa de guanábana con leche de coco y hielo'),
    dict(title='Sopa de yuca con pollo', meal_block='almuerzo', calories_estimate=400,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Sopa de yuca con pollo y cilantro'),
    dict(title='Mango biche con sal y limón', meal_block='merienda', calories_estimate=60,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Mango verde picado con sal, limón y ají al gusto'),
    dict(title='Crema de zanahoria y jengibre', meal_block='cena', calories_estimate=170,
         goal_tags=['fat_loss', 'general_health'], fitness_level_min=1, fitness_level_max=5,
         description='Crema de zanahoria con jengibre fresco y un toque de coco'),
    dict(title='Galletas de avena caseras con café', meal_block='media_manana', calories_estimate=180,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=5,
         description='2 galletas de avena y miel con tinto o aromática'),
    dict(title='Arroz de leche con canela', meal_block='cena', calories_estimate=290,
         goal_tags=['general_health'], fitness_level_min=1, fitness_level_max=4,
         description='Postre ligero de arroz en leche con canela y panela'),
    dict(title='Bowl proteico de desayuno', meal_block='desayuno', calories_estimate=440,
         goal_tags=['muscle_gain', 'fat_loss'], fitness_level_min=4, fitness_level_max=5,
         description='Yogur griego, proteína en polvo, granola, maní y fruta'),
    dict(title='Sopa de cebolla con queso', meal_block='cena', calories_estimate=230,
         goal_tags=['general_health', 'fat_loss'], fitness_level_min=1, fitness_level_max=5,
         description='Sopa de cebolla gratinada con queso bajo en grasa'),
    dict(title='Plátano en leche', meal_block='merienda', calories_estimate=230,
         goal_tags=['general_health', 'muscle_gain'], fitness_level_min=1, fitness_level_max=5,
         description='Plátano maduro cocido en leche con canela, postre y merienda tradicional'),
]


class Command(BaseCommand):
    help = 'Seed Colombian meal suggestions into MealSuggestion table'

    def handle(self, *args, **options):
        created = updated = 0
        for data in SUGGESTIONS:
            obj, was_created = MealSuggestion.objects.update_or_create(
                title=data['title'],
                meal_block=data['meal_block'],
                defaults={k: v for k, v in data.items() if k not in ('title', 'meal_block')},
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(
            f'Meal suggestions: {created} created, {updated} updated — total {created + updated}'
        ))
